### ISSUE TITLE
Sift.get() returns null if the app UI hasn't been launched yet

### ISSUE THREAD

**Issue by edenman** [SiftScience/sift-android#10]
My app has a boot listener so that we can fetch the state of the world from our server and stop/re-start Geofences as needed.  Because of the way the documentation says to initialize Sift, none of my Activity listener stuff has fired yet, because there's no UI yet.  But my `User` listener fires, and that means I call `Sift.get().userId = foo`.  Unfortunately this means the app crashes because `Sift.get()` is null.

What should I do here?  With the way you guys have structured things, it's pretty clear that the Sift lifecycle is supposed to mirror the Activity lifecycle, but that means out-of-band things like this have nowhere to go.

**Comment by edenman** [comment]
At the very least, `Sift.get()` should be marked `@Nullable`

**Comment by garylee1** [comment]
@edenman we've market `Sift.get()` as nullable and will make a release sometime this week.

**Comment by garylee1** [comment]
Done
