### ISSUE TITLE
Proguard configuration

### ISSUE THREAD

**Issue by sleepylee** [SiftScience/sift-android#12]
Our app failed at init when trying to integrate SiftScienece with proguard mode is On. Here is what we received from the crashlytics http://crashes.to/s/9b9d8fcf881. Would you please advise for the solution? 
Currently what I suppose is that there is some extra configuration required for the usage jackson usage https://github.com/FasterXML/jackson-docs/wiki/JacksonOnAndroid

**Comment by garylee1** [comment]
Thanks for the report @sleepylee – have you tried incorporating the set of proguard configs you linked there? We have some rules for Jackson already (see https://github.com/SiftScience/sift-android/blob/master/sift/proguard-rules.pro) but maybe we can add more they fix things for you.

**Comment by sleepylee** [comment]
thanks for the reply @garylee1, I think this should work from now since we don't observe this issue re-surfaced anymore (with the extras configuration I added from my project's proguard).
