### ISSUE TITLE
Application Crash when call Sift.open

### ISSUE THREAD

**Issue by brunogabriel** [SiftScience/sift-android#13]
Hi,

I'm integrating Sift using Android SDK, when I call Sift.open(activity), the application crash. The error is:

```
java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzq, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
                                                                                  at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
                                                                                  at siftscience.android.AppStateCollector.<init>(AppStateCollector.java:62)
```
I tried to use with exclude and without in gradle dependencies:
def SIFT_VERSION = '0.9.5'
// Sift
    compile ("com.siftscience:sift-android:$SIFT_VERSION", {
        exclude group: 'com.google.android.gms', module: 'play-services-location'
        exclude group: 'com.google.android.gms', module: 'play-services-auth'
    })

**Comment by quanpod** [comment]
Thanks @brunogabriel, thanks for the report - adding @garylee1 who's going to help take a look.

**Comment by garylee1** [comment]
Hey @brunogabriel thanks for the report. Please see this thread for the fix and feel free to reopen this issue if it doesn't work: https://github.com/SiftScience/sift-android/issues/9
