### ISSUE TITLE
Memory leak upon app launch

### ISSUE THREAD

**Issue by weilun106** [SiftScience/sift-android#17]
Per my colleague @tomoima525:

We followed [Application Integration section](https://siftscience.com/developers/docs/curl/mobile-sdk/android) to implement Sift Science SDK. However, We are seeing memory leaks at LaunchActivity which gets destroyed immediately(1 - 5 sec) after app launch. I'm suspecting that Sift.collect() is taking a long time to collect data and since devicePropertiesCollector holds a strong reference to Activity context, it is causing the memory leak.

5-10MB of memory leak is huge and we can not overlook. So we end up can only choose not to integrate the SDK at this point.

Should we not call this method at LaunchActivity? Does anyone at Sift Science has a workaround for it?

**Comment by garylee1** [comment]
Hi – for I think a reasonable fix would be to remove this from LaunchActivity and initialize the Sift SDK elsewhere. We will look into fixing this memory leak in an upcoming sprint. Thanks for the report!

**Comment by garylee1** [comment]
Update @weilun106 – we have a fix for the memory leak and are targeting a release this Thursday or Friday. Thank you for your patience!

**Comment by garylee1** [comment]
Hi @weilun106 – we're planning on releasing the fix today!

**Comment by garylee1** [comment]
This has been released with 0.9.8!
