### ISSUE TITLE
Documentation not correct re: disallow location, causes crash

### ISSUE THREAD

**Issue by TomGilbert** [SiftScience/sift-android#27]
The sample code for `onActivityCreated` doesn't use the API correctly with regards to `withDisallowLocationCollection`. The sample shows a call to `Sift.get().setConfig(...)` AFTER a call to `Sift.open(activity)`. The open call will try to init location services and will therefore crash on a Android 6+ device when the app doesn't have location permissions.

The correct form is to instead supply the config as second parameter of the open call:
```
public void onActivityCreated(Activity activity, Bundle bundle) {
    Sift.open(activity, new Sift.Config.Builder()
        .withAccountId("YOUR_ACCOUNT_ID")
        .withBeaconKey("YOUR_BEACON_KEY")                
        // Uncomment to disallow location collection
        //.withDisallowLocationCollection(true)
        .build());
    Sift.collect();
}
```

**Comment by garylee1** [comment]
Thanks for this! We've updated the docs with 0.9.10 (just released).
