### ISSUE TITLE
Sift AndroidManifest.xml shouldn't include location permissions

### ISSUE THREAD

**Issue by TomGilbert** [SiftScience/sift-android#28]
Surely the documentation should tell the app dev to add location permissions to the app AndroidManifest.xml *iff* the app is going to use location tracking?

If these permissions are included in Sift's manifest as they are now, everything is probably OK for API 23+ (Android 6.0) since they are requested as runtime permissions. 

However for versions of Android before API 23, a user MUST grant these permissions before they can install the app from the Play Store, even if the app doesn't plan to enable Sift's location tracking. This can cause existing users to refuse to update to a new version, or new users to install the app in the first place.

**Comment by TomGilbert** [comment]
The problem noted above for API versions < 23 (when *not* using Sift location stuff) can be avoided by adding this to the app AndroidManifest.xml

```<!-- remove Sift Science SDK unwanted permissions -->
    <uses-permission
        android:name="android.permission.ACCESS_COARSE_LOCATION"
        tools:node="remove" />
    <uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION"
        tools:node="remove" />```

**Comment by ming13** [comment]
@garylee1, any updates on this?

**Comment by garylee1** [comment]
hey @ming13 thanks for your patience – we're planning on doing a release soon and can roll this in.

**Comment by garylee1** [comment]
@TomGilbert @ming13 we've just released a significant upgrade to the SDK and have removed the optional permissions from our AndroidManifest.xml among many other improvements. The release can be found here:

https://github.com/SiftScience/sift-android/releases/tag/v0.10.0-beta

Please do observe the release notes – there are a few breaking changes that require very minor integration tweaks and some optional new features as well.

**Comment by garylee1** [comment]
@TomGilbert @ming13 please upgrade to the latest version – [0.10.1-beta](https://github.com/SiftScience/sift-android/releases/tag/v0.10.1-beta). We've made a few patches.
