### ISSUE TITLE
Build error for archiveConfig

### ISSUE THREAD

**Issue by NightOwlCoder** [SiftScience/sift-android#35]
Build error on this file:

https://github.com/SiftScience/sift-android/blob/90d264ecd152e378f71f7b55fbbda031584b1368/sift/src/main/java/siftscience/android/Sift.java

This 2 methods are duplicated:

```
String archiveConfig()
Config unarchiveConfig(String archive, Config c)
```

**Comment by garylee1** [comment]
Ah, sorry about this – I was pretty sure I caught this but it didn't make its way into the release. Will have the fix out very soon.

**Comment by garylee1** [comment]
Actually @NightOwlCoder – are you trying to build it from the Github artifact? I believe the release on jcenter / maven does not have this issue.

**Comment by garylee1** [comment]
In any case, I'll push another Github release with this fixed.

**Comment by garylee1** [comment]
@NightOwlCoder this has been fixed and rereleased under 0.9.12

**Comment by NightOwlCoder** [comment]
@garylee1 yes, we build from GitHub, is that bad?
What would be a good way to build it?

We need the AAR to create the Xamarin bindings.

**Comment by NightOwlCoder** [comment]
Thank you for the quick turn around.
