### ISSUE TITLE
Can t provide Sift for instance

### ISSUE THREAD

**Issue by serapbercin** [SiftScience/sift-android#41]
SiftScience version to 0.9.13

about the this method
@Nullable
    public static synchronized Sift get() {
        return instance;
    }

I cant provide Sift instance because of use  Nullable annotation in Sift get()

**Comment by garylee1** [comment]
@serapbercin Just curious why you're trying to access the instance? We're also making a release this week that operates entirely on the Singleton class, so that should solve this.

**Comment by alteredworlds** [comment]
The docs for a [custom integration ](https://github.com/SiftScience/sift-android#custom) contain the line `Sift.get().save();`, to be called in onPause(), so I've implemented as:
```// Sift Science
        if (BuildConfig.ENABLE_SIFT) {
            final Sift sift = Sift.get();
            if (null != sift) {
                sift.save();
            }
        }

**Comment by garylee1** [comment]
@serapbercin @alteredworlds – we've just released a significant upgrade to the SDK which removes instance access altogether, so hopefully that should address your issue. It can be found here:

https://github.com/SiftScience/sift-android/releases/tag/v0.10.0-beta

Please do observe the release notes – there are a few breaking changes that require very minor integration tweaks and some optional new features as well.

**Comment by garylee1** [comment]
@serapbercin please upgrade to the latest version – [0.10.1-beta](https://github.com/SiftScience/sift-android/releases/tag/v0.10.1-beta). We've made a few patches.
