### ISSUE TITLE
Sift.setUserId and Sift.unsetUserId throw NullPointerException

### ISSUE THREAD

**Issue by PavKovalenko** [SiftScience/sift-android#49]
Found that calling Sift.setUserId and Sift.unsetUserId can throw NullPointerException.
Looks like it can happens if calling them outside Activity lifecycle. It could happens if need to setup user Id or clear it inside async callback.
User already close activity and application need to setup Id, but Instance field inside field is null.
I added handling this situation inside my application, but maybe would be better to handle this inside Sift.

**Comment by quanpod** [comment]
Acknowledging, @garylee1 to investigate.  Thanks for the report @PavKovalenko

**Comment by garylee1** [comment]
@PavKovalenko what SDK version are you on?

**Comment by garylee1** [comment]
we fixed this with 0.10.1-beta – we never close the Sift instance so as long as you open it before you `setUserId` anywhere, you should never get an NPE

**Comment by PavKovalenko** [comment]
@garylee1 Thank you. Then we can close issue
