### ISSUE TITLE
Updating Sift.Confg

### ISSUE THREAD

**Issue by sidnair** [SiftScience/sift-android#55]
Hi,

Is there a way to change the account id/secret if `Sift.open()` has already been called? It looks like `Sift.open()` ignores the config if a `SiftImpl` exists, and the `setConfig()` method in `SiftImpl` isn't exposed by the `Sift` singleton.

The context is that in the test build of our app, users can configure whether they hit our staging or prod API. So, when the user switches environments, I want to update the Sift config to use the appropriate keys and call `Sift.collect()`.

**Comment by garylee1** [comment]
@sidnair Ah sure, that's reasonable. I will put that on the list for our next release.

**Comment by sidnair** [comment]
Awesome, thanks. Do you have a sense of timing, so we can figure out how to prioritize workarounds in the meantime?

**Comment by garylee1** [comment]
I'll try to have something by end of next week

**Comment by garylee1** [comment]
@sidnair I just released 0.10.3-beta, which will apply a new config when `Sift.open(context, config)` is called.l
