### ISSUE TITLE
Proguard rules are way too broad

### ISSUE THREAD

**Issue by hvisser** [SiftScience/sift-android#59]
The ProGuard config is keeping all of the library, preventing shrinking of unused code. In addition it's also keeping entire third party libraries and very generic package names like `com.google.common`.

It also "removes" logging by using `-assumenosideeffects` but this _only_ works if ProGuard optimisation is enabled. This may not be the case for every Android build out there, resulting in debug logging that includes things like user emails in release builds.

**Comment by quanpod** [comment]
Thanks @hvisser - acknowledging the request.  Assigning to @garylee1 for the moment, I'll have Laura and team connect us for some more details here.

**Comment by garylee1** [comment]
@hvisser we've significantly reduced our ProGuard footprint with https://github.com/SiftScience/sift-android/releases/tag/v0.10.4. We still need to work on the logging bit and previously we were having some issues with shrinking things due to schema serialization, but I will keep you posted!
