### ISSUE TITLE
Unable to build app with gradle 3.1.3 and sift 0.10.3-beta

### ISSUE THREAD

**Issue by elaser** [SiftScience/sift-android#60]
Hi there,
  We tried to integrate Sift Science with our app (which is currently being built on gradle 3.1.3).  We tried 0.10.3-beta and 0.9.2 as well.  We are encountering this error:

```
AGPBI: {"kind":"error","text":"Program type already present: javax.annotation.PostConstruct","sources":[{}],"tool":"D8"}
:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
:app:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
```

Do you have a workaround for this?

**Comment by quanpod** [comment]
Acknowledging the request and assigning @garylee1.  My initial instinct is that there are some issues around the dependencies you're pulling in and some overlapping ones w/ what Sift pulls in.

**Comment by garylee1** [comment]
@elaser this has been fixed with https://github.com/SiftScience/sift-android/releases/tag/v0.10.4!

**Comment by quanpod** [comment]
For clarification, there were still some overlapping dependencies that caused this particular build issue.  We went ahead and finished out some additional work to remove dependencies that were no longer needed to make the SDK more compact, let us know if there are more issues and we're happy to help.

**Comment by elaser** [comment]
works great -- thank you @garylee1 !
