### ISSUE TITLE
Multidex Support

### ISSUE THREAD

**Issue by theonetheycallneo** [SiftScience/sift-android#66]
Hello,

We were attempting to install Sift in our Android application.  However our app is quite large and has multiDex enabled https://developer.android.com/studio/build/multidex

When we add the Sift lib, we receive an error:

```
Picked up _JAVA_OPTIONS: -Xmx2048M

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.
```

Any ideas and help would be much appreciated.

**Comment by quanpod** [comment]
Acknowledging the request - I'm adding @garylee1 and @ehrmann to do an initial look.

**Comment by quanpod** [comment]
@theonetheycallneo could you also please send me an email - quan@sift.com in case we need some additional details?

**Comment by quanpod** [comment]
I did a quick look around the web and this has been seen in some other libraries, particularly in relation to Google services dependencies or a Gradle cache issue.  

Could you share the dependency list/build.gradle file? 

I've been looking over here: https://github.com/invertase/react-native-firebase/issues/1051

**Comment by theonetheycallneo** [comment]
> @theonetheycallneo could you also please send me an email - [quan@sift.com](mailto:quan@sift.com) in case we need some additional details?

Shot you an email with more details.  Thanks for your help-

**Comment by theonetheycallneo** [comment]
I was able to fix this by installing the latest android gradle plugin and updating my dependencies.

```
buildscript {
    ext {
        minSdkVersion       = 19
        compileSdkVersion   = 28
        targetSdkVersion    = 28
        buildToolsVersion   = "28.0.3"
        supportLibVersion   = "28.0.0"
    }
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:4.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```
