### ISSUE TITLE
Crash in AppStateCollector.getIpAddresses

### ISSUE THREAD

**Issue by BruceClift** [SiftScience/sift-android#67]
I am using your library (com.siftscience:sift-android:0.10.4), and am seeing this crash (so far only for one of my users):
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Enumeration.hasMoreElements()' on a null object reference
       at siftscience.android.AppStateCollector.getIpAddresses(AppStateCollector.java:172)
       at siftscience.android.AppStateCollector.get(AppStateCollector.java:150)
       at siftscience.android.AppStateCollector.doCollect(AppStateCollector.java:127)
       at siftscience.android.AppStateCollector.collect(AppStateCollector.java:90)
       at siftscience.android.Sift$1.run(Sift.java:106)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)

Looking at your code, AppStateCollector.getIpAddresses has this:
        for (Enumeration<NetworkInterface> en = NetworkInterface.getNetworkInterfaces();
             en.hasMoreElements(); ) {

However, in Android library 28 the function getNetworkInterfaces sometimes returns null. It actually has a comment explaining the null return:
        // Android-changed: Rewrote NetworkInterface on top of Libcore.io.
        // specified to return null if no network interfaces

Thus you need to make a minor modification to `getIpAddresses` so you check for null before starting the for loop.
    Enumeration<NetworkInterface> en = NetworkInterface.getNetworkInterfaces();
    if (en != null) {
        while (en.hasMoreElements) { ... }

**Comment by quanpod** [comment]
Thanks Bruce - acknowledging the request. Tagging in David and Gary to take
a look.

**Comment by quanpod** [comment]
Update: this is fixed in the latest version, @garylee1 will update Github with the latest release shortly and we'll close this out.

**Comment by garylee1** [comment]
The fix has been released to both Maven and Github – https://github.com/SiftScience/sift-android/releases/tag/v0.10.5

Thank for your patience, and for your surfacing this!
