### ISSUE TITLE
Github Readme Documentation is not up to date

### ISSUE THREAD

**Issue by 20ali20** [SiftScience/sift-android#72]
Current Documentation in Readme file is not up to date with the latest version available and some of its functions are deprecated. 

an example :  Sift.save() is no longer available.

**Comment by langsmith** [comment]
Yep @20ali20, this was confusing for me as I got up-to-speed with the SDK. Hopefully they'll fix the README by approving and merging my pr at https://github.com/SiftScience/sift-android/pull/87.

**Comment by brianmhiggins** [comment]
Thank you for the change.  I have merged #87 and will close this issue

**Comment by langsmith** [comment]
Thanks @brianmhiggins
