### ISSUE TITLE
Does not support TV devices

### ISSUE THREAD

**Issue by gmctaggart-patreon** [SiftScience/sift-android#78]
AppStateCollector.java crashes when attempting to gather battery status for devices that do not provide battery information such as smart TVs.

Here is a sample from Firebase Crashlytics:
<img width="1264" alt="Screen Shot 2020-10-27 at 1 41 52 PM" src="https://user-images.githubusercontent.com/66275960/97359895-b81d8e00-185a-11eb-8ebd-4ea768a33dee.png">

**Comment by viaskal-sift** [comment]
Hi @gmctaggart-patreon , closing this one cause the issue was addressed already in this version - https://github.com/SiftScience/sift-android/releases/tag/v0.11.1
