### ISSUE TITLE
Add `Sift.getUserId()` method?

### ISSUE THREAD

**Issue by langsmith** [SiftScience/sift-android#88]
As I get up-to-speed with the SDK and check that I've got everything installed correctly, I've found that it'd be really helpful to have a public `getUserId()` method. This way, I could check to see whether any user ID has been set at a certain point in my app's flow and if so, what the ID is. Right now, there's only `setUserId()` but no getter 😕

**Comment by langsmith** [comment]
Although the user ID gets printed to the logcat 👇🏽 , I still think it'd be great to have a method....

<img width="189" alt="Screen Shot 2021-03-16 at 7 28 12 PM" src="https://user-images.githubusercontent.com/4394910/111405506-d828df00-868d-11eb-8ef0-f3336df13828.png">

**Comment by viaskal-sift** [comment]
@langsmith is this still an issue for you? If yes, we will introduce the method in one of the upcoming releases

**Comment by langsmith** [comment]
I no longer work at the company that's using Sift, but I still strongly encourage y'all to add it to your SDK. This type of method is pretty standard in serious/large/commercial SDKs.  It'd be beneficial for users to have as an option and I'd guess it's be pretty lightweight for y'all to add.

**Comment by viaskal-sift** [comment]
Thanks a lot @langsmith for the feedback, we will scope that
