### ISSUE TITLE
Update Gson dependency version due to vulnerability

### ISSUE THREAD

**Issue by J-Mendes** [SiftScience/sift-android#96]
Hey, I've noticed that there is a security vulnerability affecting the GSON library that can compromise the data being deserialized.
Can you update the dependency to the latest one to overcome this?

You can follow the GSON issue [here](https://github.com/google/gson/pull/1991) and if you want more details about what it may affect [here](https://ossindex.sonatype.org/vulnerability/sonatype-2021-1694?component-type=maven&component-name=com.google.code.gson%2Fgson)

Thanks

**Comment by noobpm** [comment]
any update on this?

**Comment by vincent-sift** [comment]
Hi @noobpm. Thanks for pinging us on this issue, it looks like this has slipped through the cracks. I will create an internal ticket and assign it out.
